apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-demo-eso
  namespace: kargo-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: css-volue-shared-dev-kv
  target:
    name: kargo-demo-credentials
    creationPolicy: Owner

    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "false"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "false"
  data:

  - secretKey: githubAppID
    remoteRef:
      key: kargo-github-app-id
  - secretKey: githubAppInstallationID
    remoteRef:
      key: kargo-github-app-installation-id
  - secretKey: githubAppPrivateKey
    remoteRef:
      key: kargo-github-app-private-key
  - secretKey: repoURL
    remoteRef:
      key: kargo-demo-repo-url
  - secretKey: repoURLIsRegex
    remoteRef:
      key: kargo-demo-repo-regex           
