apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  subscriptions:
    warehouse: guestbook
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/akuity/kargo-simple.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/akuity/guestbook
          path: env/dev
  requestedFreight:
    - origin:
        kind: Warehouse
        name: argo-poc-warehouse
      sources:
        direct: true        
    # If you have an Argo CD application that should be synced after the git repo is updated,
    # uncomment the following lines and specify the app name. Repeat for the other Stages.
    # argoCDAppUpdates:
    # - appName: guestbook-dev

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/akuity/kargo-simple.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/akuity/guestbook
          path: env/staging
  requestedFreight:
    - origin:
        kind: Warehouse
        name: argo-poc-warehouse
      sources:
        direct: true        
    # argoCDAppUpdates:
    # - appName: guestbook-staging

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: staging
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/akuity/kargo-simple.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/akuity/guestbook
          path: env/prod
      pullRequest: {}
  requestedFreight:
    - origin:
        kind: Warehouse
        name: argo-poc-warehouse
      sources:
        direct: true  
    # argoCDAppUpdates:
    # - appName: guestbook-prod
