apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>staging</title>
    </head>
    <body>

    <h1>kargo staging</h1>

    </body>
    </html>
